services:
  worker:
    command: celery -A worker.celery_app worker --loglevel=info --pool=solo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
