channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.*
  - scipy
  - matplotlib
  - scikit-image=0.25.*
  - scikit-learn
  - imageio
  - imagecodecs
  - networkx
  - shapely
  - numcodecs
  - tqdm
  - joblib
  - pydantic
  - packaging
  - fonttools
  - blessed
  - fasteners
  - msgpack-python
  - pyyaml
  - pip:
      - ashlar==1.19.0
      - filelock
      - fire
      - fsspec
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - pillow>=10
      - simple-lama-inpainting
      - torch==2.7.1
      - torchvision==0.22.1
      - opencv-python
      - pyjnius==1.6.1
      - termcolor
      - sympy
      - typing-extensions
      - tifffile>=2026.3.3
      - zarr>=3.1.6
