channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.*
  - scipy
  - matplotlib
  - scikit-image=0.25.*
  - scikit-learn==1.6.1
  - imageio
  - imagecodecs
  - networkx
  - shapely
  - numcodecs=0.14.1
  - zarr=2.*
  - tqdm
  - joblib
  - pydantic
  - packaging
  - fonttools
  - blessed
  - fasteners
  - msgpack-python
  - pyyaml
  - pip:
      - numpy==1.26.4
      - fire==0.5.0
      - ashlar==1.19.0
      - filelock
      - fire
      - fsspec
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - pillow==9.5.0
      - torch==2.7.1
      - torchvision==0.22.1
      - opencv-python
      - pyjnius==1.6.1
      - termcolor
      - sympy
      - typing-extensions
      - tifffile==2024.12.12
