"""Grid refinement step to post-process detection results."""

from typing import Any, Dict, List, Optional

import cv2
import joblib
import numpy as np

from src.core.step import PipelineStep
from config.config_schema import GridRefinementConfig
from src.utils.detection.models import DetectionStrategy, Orientation, DetectionRegion
from src.utils.detection.contour_analysis import analyze_contour
from src.core.container import Container


class GridRefinementStep(PipelineStep):
    """Pipeline step for refining grid detection results."""

    def __init__(self, config: GridRefinementConfig, name: str = "grid_refinement", **kwargs: Any) -> None:
        """Initialize grid refinement step with configuration."""
        super().__init__(name=name, config=config, **kwargs)

        if config is None:
            raise ValueError(f"[{name}] GridRefinementConfig is required")

        self.model = joblib.load(config.classifier.model_path)
        self.log(
            f"Loaded refinement model from {config.classifier.model_path}")

    def _refine_border_detections(self, contour_dicts: List[dict], orientation, strategy) -> List[dict]:
        """
        Refine border detections using the classifier.

        Args:
            contour_dicts: List of contour dictionaries.
            orientation: Orientation enum.
            strategy: DetectionStrategy enum.

        Returns:
            List of top contours after refinement.
        """
        scored_contours: List[tuple[float, dict]] = []
        orientation_name = orientation.value if hasattr(orientation, "value") else str(orientation)
        for idx, item in enumerate(contour_dicts):
            contour = item.get("contour")
            if contour is None:
                continue

            analysis = analyze_contour(
                contour,
                orientation=orientation,
                strategy=strategy,
                image_shape=Container.resolve("pipeline_context").image_shape
            )

            feature_values = []
            for feature in self.config.classifier.features:
                value = analysis.get(feature)
                if value is None:
                    value = 0.0
                feature_values.append(value)

            probability = self.model.predict_proba([feature_values])[0][1]

            self.debug(
                f"Contour {idx + 1}: probability={probability:.3f}, threshold={self.config.classifier.threshold}")

            if probability > self.config.classifier.threshold:
                scored_contours.append((probability, item))

        # Rank remaining contours by probability and keep only the top one per orientation
        if scored_contours:
            scored_contours.sort(key=lambda x: x[0], reverse=True)
            top_contours = [scored_contours[0][1]]
        else:
            top_contours = []

        self.debug(
            f"Kept {len(top_contours)}/{len(contour_dicts)} {orientation_name} contours after refinement"
        )

        return top_contours


    def run(self, data: Any) -> tuple[Dict[str, Any], Optional[dict]]:
        """Refine detection results by analyzing non-general contours.

        Args:
            data: results dict from grid detection step.

        Returns:
            Tuple containing refined results and original metadata.
        """
        if not isinstance(data, dict):
            raise TypeError("GridRefinementStep expects results dictionary")

        detections = data.get("detections", {})
        strategies = data.get("strategies", {})

        refined: Dict[Orientation, Any] = {}

        for orientation, contour_dicts in detections.items():
            strategy = strategies.get(orientation)
            orientation_name = orientation.value if hasattr(
                orientation, "value") else str(orientation)

            if strategy == DetectionStrategy.GENERAL:
                self.debug(
                    f"Keeping {len(contour_dicts)} {orientation_name} contours from general detection"
                )

                contours = [c.get("contour") for c in contour_dicts if c.get("contour") is not None]

                if len(contours) > 1:
                    self.debug(
                        f"Merging {len(contours)} contours for {orientation_name} orientation"
                    )
                    merged = cv2.convexHull(np.vstack(contours))
                    zone = contour_dicts[0].get("zone", DetectionRegion.CENTER)
                    refined[orientation] = [{"contour": merged, "zone": zone}]
                else:
                    refined[orientation] = contour_dicts
                continue

            # Analyze contours generated by any other strategy and use the classifier to filter the ones that are not an actual detection
            self.debug(
                f"Analyzing {len(contour_dicts)} {orientation_name} contours from {getattr(strategy, 'value', strategy)} detection")

            top_contours = self._refine_border_detections(contour_dicts, orientation, strategy)

            refined[orientation] = top_contours

        refined_results = {"detections": refined, "strategies": strategies}
        return refined_results, None
