"""Grid refinement step to post-process detection results."""

from typing import Any, Dict, List, Optional

from core.step import PipelineStep
from config.config_schema import GridRefinementConfig
from utils.detection.models import DetectionStrategy, Orientation
from utils.detection.contour_analysis import analyze_contour

import joblib


class GridRefinementStep(PipelineStep):
    """Pipeline step for refining grid detection results."""

    def __init__(self, config: GridRefinementConfig, name: str = "grid_refinement", **kwargs: Any) -> None:
        """Initialize grid refinement step with configuration."""
        super().__init__(name=name, config=config, **kwargs)

        if config is None:
            raise ValueError(f"[{name}] GridRefinementConfig is required")

        self.model = joblib.load(config.classifier.model_path)
        self.log(f"Loaded refinement model from {config.classifier.model_path}")


    def run(self, data: Any) -> tuple[Dict[str, Any], Optional[dict]]:
        """Refine detection results by analyzing non-general contours.

        Args:
            data: Tuple of (results, metadata) from grid detection step.

        Returns:
            Tuple containing refined results and original metadata.
        """
        if not isinstance(data, tuple) or len(data) != 2:
            raise TypeError("GridRefinementStep expects (results, metadata) tuple")

        results, metadata = data
        if not isinstance(results, dict):
            raise TypeError("GridRefinementStep expects results dictionary")

        detections = results.get("detections", {})
        strategies = results.get("strategies", {})
        refined: Dict[Orientation, Any] = {}

        for orientation, contour_dicts in detections.items():
            strategy = strategies.get(orientation)
            orientation_name = orientation.value if hasattr(orientation, "value") else str(orientation)

            if strategy == DetectionStrategy.GENERAL:
                self.debug(
                    f"Keeping {len(contour_dicts)} {orientation_name} contours from general detection"
                )
                refined[orientation] = contour_dicts
            else:
                self.debug(
                    f"Analyzing {len(contour_dicts)} {orientation_name} contours from {getattr(strategy, 'value', strategy)} detection"
                )
                
                # TODO. Analyze contours generated by any other strategy and use the classifier to filter the ones that are not an actual detection

        refined_results = {"detections": refined, "strategies": strategies}
        return refined_results, metadata